#string  定义openapi的规范版本号  必须参数
openapi: 3.0.1
#信息对象  提供有关api的元数据  必须参数
info:
  #string  应用程序的名称  必须参数
  title: my demo
  #string  应用程序简单描述
  description: openapi 生成实例
  #string  api服务条款网址
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  #Object  公开api许可信息
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
#服务器对象数组  用于提供目标服务器的连接信息  如果不提供，默认将是一个有url的服务器对象
servers:
  - url: https://myDemo/api
    description: Development server
    variables:
      username:
        default: wkn
        description: default user
      port:
        enum:
          - '8080'
          - '8088'
        default: '8080'
      basePath:
        default: v2
#-- /{path}   path项对象  到单个短线的相对路径，字段名称必须以/开头，路径会自动追加到url后面，用以构造完成的url
paths:
#--   王康宁的接口  起始线-----------------------------------
  /totalRanking:
    get:
      description: 工时/任务排行
      summary: 工时/任务排行
      tags:
        - ranking
      operationId: totalRanking
      parameters:
        - name: flag
          in: query
          description: 0：工时 1：任务数
          schema:
            type: integer
        - name: startDate
          in: query
          description: 开始日期
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: 结束日期
          schema:
            type: string
            format: date
      responses:
        '200':
          description: 返回用户信息
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'wkn.yml#/rankMessageAllDTO'
#--   王康宁的接口  终止线-----------------------------------

